### ISSUE TITLE
use static image.

### ISSUE THREAD

**Issue by chirag04** [naoufal/react-native-activity-view#1]
Is it possible to use static image in the app instead of loading it from a url/network?

Definitely want to use this component in my app. Thanks for this. :)

**Comment by naoufal** [comment]
It's definitely possible.  I'm trying to figure out the best way of doing this without needing to setup assets within Xcode.  My current plan is to support `imageBase64`.  

Let me know if that would cover your use case.

**Comment by chirag04** [comment]
My usecase is to just give the logo as image. Logo is already added in the assets within xcode.
I think this is a very common usecase. 

Not sure what imageBase64 is. I'm really new to ios world.

**Comment by naoufal** [comment]
It's essentially encrypting the image into a string that could be past to the module.  More on Base64 [here](http://en.wikipedia.org/wiki/Base64).

I'll see if I can get around to closing this issue sometime this week.

**Comment by chirag04** [comment]
I think using ``[UIImage imageNamed: image]`` should solve the problem. We can support ``imageUrl`` and ``image``. image would load images in the bundle using ``[UIImage imageNamed: image]`` and imageUrl would fetch using network.


I have a working implementation of this. Happy to PR. Let me know.

**Comment by naoufal** [comment]
Awesome! Providing an `image` and `imageUrl` key is how I was planning to support it too. 

A PR would be great :+1:

**Comment by chirag04** [comment]
done. Looking forward to getting this merged and a version bump.
