### ISSUE TITLE
Crashes on iPads for iOS 8+

### ISSUE THREAD

**Issue by isair** [naoufal/react-native-activity-view#12]
Since the new UIPopoverPresentationController is used for presentation, some additional setup needs to be done.

**Comment by chirag04** [comment]
@isair Can you PR?

Wondering if this is affecting react native also. 
refer: https://github.com/facebook/react-native/blob/master/Libraries/ActionSheetIOS/RCTActionSheetManager.m#L88-L113

**Comment by naoufal** [comment]
@isair Can you post a video with a repro?

**Comment by chirag04** [comment]
@naoufal  I just reproduced this on ipad simulator. 

Got the below error:
```
UIAlertControllerActionSheetRegularPresentationController: 0x7fcbaa7dad80>) should have a non-nil sourceView or barButtonItem set before the presentation occurs
```

**Comment by naoufal** [comment]
@chirag04 On what device and which iOS?

**Comment by chirag04** [comment]
ipad 8.4 I think you can replicate this on ios 8+ and ipad simulator

**Comment by naoufal** [comment]
Does one of you have time to tackle this?

**Comment by chirag04** [comment]
I think i have a fix but i'm not sure if its good enough.

Going by the answer here: http://stackoverflow.com/questions/25644054/uiactivityviewcontroller-crashing-on-ios8-ipads

I just added these lines below line 50 here: https://github.com/naoufal/react-native-activity-view/blob/master/ActivityView.m#L50

```
    // fix for ipad.
    if ( [activityView respondsToSelector:@selector(popoverPresentationController)] ) {
        activityView.popoverPresentationController.sourceView = ctrl.view;
    }

```

**Comment by isair** [comment]
That will make the UIActivityViewController pop up from the top left of the screen.

![screen shot 2015-08-21 at 12 36 36 am](https://cloud.githubusercontent.com/assets/988213/9403364/1feb24c6-47ef-11e5-8ad0-ebf74be3a4b6.png)

Ideally, we want to pass the view which was interacted to show the activity view. Like a share button. But a quick fix can be to just add an optional frame parameter to ActivityView.show method.

**Comment by naoufal** [comment]
Interesting approach. 

Do you guys know if `UIModalPresentationFormSheet` supports the `ActivityViewController`?

If it does, it would be a good default as it doesn't require users to pass additional arguments.

**Comment by chirag04** [comment]
@isair  can we wait for someone on react-native repo to talk about the api to fix this? I like your approach but want to wait and see what fb guys thinks about this api.

**Comment by isair** [comment]
@naoufal Probably not, but will check.

@chirag04 I'm curious about that too. I just had to make this work on iPads urgently so I put together a solution really fast.

**Comment by paramaggarwal** [comment]
Yes, this is consistent on this library itself and also on the React Native's implementation.

Please refer here for fix: https://github.com/facebook/react-native/issues/2604
