### ISSUE TITLE
Unable to resolve module invariant

### ISSUE THREAD

**Issue by asamiller** [naoufal/react-native-activity-view#18]
After updating to 0.2.5 I get this error from the packager: `Unable to resolve module invariant from ActivityView.ios.js`

This is with React Native 0.11.0

**Comment by chirag04** [comment]
+1

@naoufal invariant is not used anywhere but it is still ``required``

Also, happy to maintain this module if you would like some more hands. You can add me as contributor if you like.

**Comment by naoufal** [comment]
> You can add me as contributor if you like.

@chirag04 Adding you to a contributor is the least I can do-- You've done a lot for this project. :)

> happy to maintain this module if you would like some more hands

That could work out, but before doing that I'd like to setup a roadmap and contributing guidelines first to have this module continue growing in the direction we want it to.  Perhaps we could discuss on Reactiflux/Hangout this weekend.

**Comment by chirag04** [comment]
Awesome. Thanks for adding me.

Let's definitely setup roadmap and contributing guidelines. I'm available on Reactiflux. Feel free to ping anytime you like.

**Comment by grabbou** [comment]
Hey guys, just wanted to add in few cents since I am using this in a bunch of production projects already. I'd love to see a roadmap or what are the plans regarding further development. And again - if you need any help, let me know. I think i've been already commenting in few issues, but I might be wrong :)

**Comment by naoufal** [comment]
Thanks for your continued interest in this module @grabbou.  I've definitely seen you comment on this repo before.  Hope it's been reliable in prod. :smile: If you can share, what's the name of the app you're using it in?

Regarding the roadmap-- When it's ready, I'll post a draft in an issue in this repo and I'll make you to tag you and chirag.

**Comment by grabbou** [comment]
Ha, thanks for the answer! The app is currently in pre-mvp so I expect it to land in the app store next week (London only unfortunately). 

It works great, currently I am running on forked version since I needed to integrate my PR before submitting the compiled bundle :)

**Comment by naoufal** [comment]
Ah cool.

I'll try and get to your PR this evening (EST) so that we can merge this in
ASAP and get you on master.

**Comment by grabbou** [comment]
Cool, no worries. Wanted to test in real app before submitting pull request anyway :) if there's anything to improve up there - let me know.
