### ISSUE TITLE
Instagram not showing up in menu

### ISSUE THREAD

**Issue by kunalnagar** [naoufal/react-native-activity-view#24]
I'm trying to share an external image to Instagram but it does not show up in the Sheet. Help?

**Comment by naoufal** [comment]
Instagram isn't supported natively in the Activity View Controller.

As far as I know Instagram doesn't have a 3rd Party Activity Extension built-in to the app either.  To see a list of the Activity Extensions supported on your phone you can press the last icon on the apps row and it'll bring up a menu with all the apps you have installed on your phone that support the Activity View.

Hope that helps.

**Comment by naoufal** [comment]
Closing since this isn't an issue with the module itself.

**Comment by 9mm** [comment]
I am not quite sure how this works yet, but is it possible to add my own custom icon that I can do some action with? I see lots of posts on SO how to share with instagram, and maybe I can make a small wrapper or something... maybe http://stackoverflow.com/questions/11393071/how-to-share-an-image-on-instagram-in-ios

**Comment by grabbou** [comment]
I think that could be easily added if we support passing `applicationActivities` instead of setting them to nil. That way, we could just register custom Instagram activity to appear in the list when share is clicked form the app.

**Comment by grabbou** [comment]
See #32 for a solution.
