### ISSUE TITLE
No Wechat sharing option

### ISSUE THREAD

**Issue by sulliwane** [naoufal/react-native-activity-view#26]
Hi,

thank you for this component. I can't find **Wechat** button in the sharing menu, any reason why? (Is it related with UIActivity).

As I understand, it's possible to **exclude** an application from the list, is it possible to add one?

Thank you!

**Comment by naoufal** [comment]
Third party apps only appear when installed on the user's device.

Therefore it isn't supported by default on this device. Hope that clears
things up.

:+1:

**Comment by sulliwane** [comment]
Wechat is installed on my phone...
thanks for your reply.

**Comment by naoufal** [comment]
I installed WeChat and it doesn't appear on the Share Sheet in Apple apps either.  Probably due to the way they configured their UIActivity.  More over at http://stackoverflow.com/a/28386421/1346653.
