### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by morenoh149** [naoufal/react-native-activity-view#29]
Beginning of thread for android support.

I believe a good approach would be to launch a fragment that overlays the current app and displays some targets to share to.
![screenshot_20160107-165824](https://cloud.githubusercontent.com/assets/587438/12183929/2111ca60-b560-11e5-9dbb-f05df13058c7.png)

**Comment by morenoh149** [comment]
overview http://developer.android.com/training/sharing/send.html

**Comment by morenoh149** [comment]
If we are allowed to use api v 23 or above we can use direct share instead. Which provides deep linking as shown in the ios gif on the readme
http://developer.android.com/about/versions/marshmallow/android-6.0.html#direct-share
https://github.com/googlesamples/android-DirectShare

**Comment by naoufal** [comment]
Hey @morenoh149, I don't plan on adding android support to this module. 

I'd rather have limit it to displaying the iOS `Activity View Controller`, hence the name of the module. 

However, I invite you to publish an Android version of this module and I would gladly link to it in the readme.

**Comment by morenoh149** [comment]
perhaps change the name of the project to `react-native-ios-activity-view` ? I would go with `react-native-android-activity-view` or `react-native-activity-view-android`.

**Comment by morenoh149** [comment]
also the choice of `yet` [here](https://github.com/naoufal/react-native-activity-view/blob/master/ActivityView.android.js#L13) was why I assumed android support would be welcome.

**Comment by naoufal** [comment]
I don't think prefixing the module name is necessary because it's named
after the iOS Class. For the same reason, I don't think
`react-native-android-activity-view` is the right name for an Android
version since the Java Classes surely have a different name.

The `index.android.js` file gets generated from the React Native Library
command. We could probably remove it if it causes confusion.

**Comment by sibeliusseraphini** [comment]
@naoufal I think you should keep this issue open, so somebody can contribute with the android version

**Comment by skleest** [comment]
I'm using "react-native-send-intent" with success.
