### ISSUE TITLE
remove platform specific reference in package.json

### ISSUE THREAD

**Issue by marcejohnson** [naoufal/react-native-activity-view#45]
I wasn't able to compile cross platform, and then I noticed in **package.json**, line 10, it says

`  "main": "ActivityView.ios.js",`

shouldn't it be:

` “main": "ActivityView”,`

"React Native will detect when a file has a .ios. or .android. extension and load the right file for each platform when requiring them from other components."  See:
https://facebook.github.io/react-native/docs/platform-specific-code.html#platform-specific-extensions

Once I made the latter change, it compiled cross platform.  This should be trivial to fix.  I can create a pull request if you like.

**Comment by naoufal** [comment]
@marcejohnson Yeah, I think 0.24 or 0.25 broke this.  Could you submit a pull-request?

**Comment by marcejohnson** [comment]
Done.  Here it is:  https://github.com/naoufal/react-native-activity-view/pull/46
