### ISSUE TITLE
Version 0.2.9 + React Native 0.22.2 does not work anymore.

### ISSUE THREAD

**Issue by livioso** [naoufal/react-native-activity-view#47]
Hi. 

Since the latest update the activity view does not show anymore: 

```
const onClickShare = (postDetail) => {
  ActivityView.show({
    text: 'Check out this cool Fashwell post.',
    url: postDetail.detail_url,
    imageUrl: postDetail.post_img_url
  });
};
```

After downgrading to 0.2.8 it works fine. Any idea why this is happening?

Cheers, Livio!

**Comment by Olliepop** [comment]
Thanks for the tip on downgrading to 0.2.8 @livioso.

The notice i get in console is `Attempting to load the view of a view controller while it is deallocating is not allowed and may result in undefined behavior`

**Comment by livioso** [comment]
@Olliepop Alright. Thanks mate! :shipit:

**Comment by ilanasufrin** [comment]
I am also experiencing this issue and downgrading fixed it.

**Comment by Elyx0** [comment]
Any news to fix that ?

**Comment by superandrew213** [comment]
Same for RN 0.24.1. Looks like it has something to do with the file sharing support that was added. @wootwoot1234 what RN version are you using and is it still working for you?
