### ISSUE TITLE
UIActivityIndicatorView Undefined

### ISSUE THREAD

**Issue by brianantonelli** [naoufal/react-native-activity-view#6]
undefined is not an object (evaluating 'NativeModules.UIManager.UIActivityIndicatorView.Constants)

React Native 0.5, Activity View 0.2.1

![screen shot 2015-06-29 at 11 09 51 am](https://cloud.githubusercontent.com/assets/454010/8410979/6925852e-1e4f-11e5-899b-6328e34dedf1.png)

**Comment by naoufal** [comment]
Hey @brianantonelli,

 ave you [linked the library](https://github.com/naoufal/react-native-activity-view#linking-the-library) in your Xcode project?

**Comment by brianantonelli** [comment]
I did, I think something in my modules got jacked up, reinstalling through NPM appears to have resolved this.

**Comment by naoufal** [comment]
Glad your issue's resolved. :smile:
