### ISSUE TITLE
fix the header search path for react-native in release scheme.

### ISSUE THREAD

**Issue by chirag04** [naoufal/react-native-activity-view#7]
Right now header search path for react-native in release scheme is ``$(SRCROOT)/../../React``.

It should just be ``$(SRCROOT)/../react-native/React`` ??

@naoufal

**Comment by naoufal** [comment]
That's right it should be.  

The `package.json` should also be updated to list `react-native` as a peerDependency for this to be accurate.

Currently, react-native is being installed as a dependency of this package and so the path would be need to `$(SRCROOT)/node_modules/react-native/React`.

**Comment by chirag04** [comment]
yeah. def. need peerDependency and then update the release/debug paths. Let me know if you need help here.

**Comment by naoufal** [comment]
@chirag04 Submitted a PR #8.  Can you review?

**Comment by chirag04** [comment]
LGTM.

**Comment by chirag04** [comment]
Thanks. Looking forward to a version bump.

**Comment by chirag04** [comment]
@naoufal  can you publish this to npm?

**Comment by naoufal** [comment]
Thanks for the reminder @chirag04. Published! https://www.npmjs.com/package/react-native-activity-view.
