### ISSUE TITLE
Header search paths are different for Debug and Release builds

### ISSUE THREAD

**Issue by isair** [naoufal/react-native-activity-view#9]
This causes release builds to fail as header search paths for release builds don't include `$(SRCROOT)/../../node_modules/react-native/React`.

**Comment by chirag04** [comment]
It is fixed but not published to npm. https://github.com/naoufal/react-native-activity-view/issues/7

**Comment by naoufal** [comment]
Sorry about the delay guys.  Just published as 0.2.2 https://www.npmjs.com/package/react-native-activity-view.

**Comment by chirag04** [comment]
@naoufal  I just updated to the latest version. Seems like the dependency path is correct but recursive option is dropped. It should be recursive in xcode header search path. 

build is breaking in both debug and release mode for now.

**Comment by naoufal** [comment]
Thanks for updating @chirag04.  I won't be able to get to this until later tonight or tomorrow.  Do you have time to submit a fix?

**Comment by chirag04** [comment]
yes. sure. on it

**Comment by chirag04** [comment]
done. Can you merge and bump the version as well.

**Comment by naoufal** [comment]
Thanks @chirag04.  Published under v0.2.3.

**Comment by chirag04** [comment]
:+1:
